"""added tables

Revision ID: 8f8981a9f13a
Revises: 36dccb2eb93d
Create Date: 2024-01-09 11:16:51.987982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8981a9f13a'
down_revision = '36dccb2eb93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=80), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_patient_name_patients'), 'patients', ['patient_name'], ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_doctor_name_doctors'), 'doctors', ['doctor_name'], ['name'])

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_doctor_name_doctors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_patient_name_patients'), type_='foreignkey')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
