"""changes

Revision ID: dd5ed1a4a214
Revises: f75955835039
Create Date: 2024-01-10 16:42:35.957270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5ed1a4a214'
down_revision = 'f75955835039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
