"""changes

Revision ID: f75955835039
Revises: 8f8981a9f13a
Create Date: 2024-01-10 16:39:37.876109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75955835039'
down_revision = '8f8981a9f13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_doctor_name_doctors', type_='foreignkey')
        batch_op.drop_constraint('fk_appointments_patient_name_patients', type_='foreignkey')
        batch_op.drop_column('patient_name')
        batch_op.drop_column('doctor_name')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_reviews_doctor_name_doctors', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_patient_name_patients', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_patient_id_patients'), 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_doctor_id_doctors'), 'doctors', ['doctor_id'], ['id'])
        batch_op.drop_column('patient_name')
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('patient_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_reviews_doctor_id_doctors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_patient_id_patients'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_patient_name_patients', 'patients', ['patient_name'], ['name'])
        batch_op.create_foreign_key('fk_reviews_doctor_name_doctors', 'doctors', ['doctor_name'], ['name'])
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('patient_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.create_foreign_key('fk_appointments_patient_name_patients', 'patients', ['patient_name'], ['name'])
        batch_op.create_foreign_key('fk_appointments_doctor_name_doctors', 'doctors', ['doctor_name'], ['name'])

    # ### end Alembic commands ###
